web:
  build: .
  dockerfile: Dockerfile-nginx
  ports:
    - "80:80"
    - "443:443"
  links:
    - php
  volumes:
    - .:/usr/share/nginx/html/attendize
    - /etc/letsencrypt/live/amba.ylecuyer.xyz/fullchain.pem:/fullchain.pem
    - /etc/letsencrypt/live/amba.ylecuyer.xyz/privkey.pem:/privkey.pem
php:
  build: .
  dockerfile: Dockerfile-php
  links:
    - db
    - redis
  volumes:
    - .:/usr/share/nginx/html/attendize
php-worker:
  build: .
  dockerfile: Dockerfile-php
  links:
    - db
    - redis
  volumes:
    - .:/usr/share/nginx/html/attendize
  command: php artisan queue:work --daemon
db:
  image: postgres
  environment:
    - POSTGRES_USER=attendize
    - POSTGRES_PASSWORD=attendize
    - POSTGRES_DB=attendize
  volumes:
    - /var/lib/postgresql/data
  ports:
    - "5432:5432"
redis:
  image: redis
